// @ts-check

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  build: [
    {
      type: "link",
      label: "Home",
      href: "/",
    },
    {
      type: "category",
      label: "JavaScript SDK",
      collapsed: false,
      link: {
        type: "doc",
        id: "build/javascript/index",
      },
      items: [
        "build/javascript/reliable-channels",
        "build/javascript/light-send-receive",
        "build/javascript/store-retrieve-messages",
        "build/javascript/message-encryption",
        "build/javascript/use-waku-react",
        "build/javascript/use-waku-create-app",
        "build/javascript/configure-discovery",
        "build/javascript/run-waku-nodejs",
        "build/javascript/debug-waku-dapp",
        "build/javascript/manage-filter",
        "build/javascript/faq",
        {
          type: "html",
          value:
            '<a href="https://examples.waku.org" target="_blank" rel="noopener noreferrer" class="menu__link external-link">@waku/sdk Examples<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.1918 4H3.42848V2.85715H13.1428V12.5714H11.9999V4.80813L3.83254 12.9755L3.02441 12.1674L11.1918 4Z" fill="white"/></svg>',
        },
        {
          type: "html",
          value:
            '<a href="https://js.waku.org" target="_blank" rel="noopener noreferrer" class="menu__link external-link">API Reference<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.1918 4H3.42848V2.85715H13.1428V12.5714H11.9999V4.80813L3.83254 12.9755L3.02441 12.1674L11.1918 4Z" fill="white"/></svg>',
        },
      ],
    },
  ],
  runNode: [
    {
      type: "link",
      label: "Home",
      href: "/",
    },
    {
      type: "category",
      label: "Run a Nwaku Node",
      collapsed: false,
      link: {
        type: "doc",
        id: "run-node/index",
      },
      items: [
        "run-node/run-docker-compose",
        "run-node/run-docker",
        "run-node/build-source",
        "run-node/configure-discovery",
        "run-node/find-node-address",
        "run-node/config-methods",
        "run-node/config-options",
        "run-node/configure-nwaku",
        "run-node/faq",
        "run-node/upgrade-instructions",
        {
          type: "html",
          value:
            '<a href="https://waku-org.github.io/waku-rest-api/" target="_blank" rel="noopener noreferrer" class="menu__link external-link">REST API Reference<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.1918 4H3.42848V2.85715H13.1428V12.5714H11.9999V4.80813L3.83254 12.9755L3.02441 12.1674L11.1918 4Z" fill="white"/></svg>',
        },
      ],
    },
  ],
  learn: [
    {
      type: "link",
      label: "Home",
      href: "/",
    },
    "learn/waku-network",
    {
      type: "category",
      label: "Concepts",
      collapsed: false,
      items: [
        "learn/concepts/protocols",
        "learn/concepts/content-topics",
        "learn/concepts/network-domains",
        "learn/concepts/transports",
        {
          type: "category",
          label: "Peer Discovery",
          link: {
            type: "doc",
            id: "learn/concepts/peer-discovery",
          },
          items: [
            "learn/concepts/static-peers",
            "learn/concepts/dns-discovery",
            "learn/concepts/discv5",
            "learn/concepts/peer-exchange",
          ],
        },
      ],
    },
    "learn/security-features",
    "learn/research",
    "learn/waku-vs-libp2p",
    "learn/glossary",
    "learn/faq",
  ],
  research: [
    {
      type: "link",
      label: "Home",
      href: "/",
    },
    {
      type: "autogenerated",
      dirName: "research",
    },
  ],
  guides: [
    {
      type: "link",
      label: "Home",
      href: "/",
    },
    "guides/getting-started",
  ],
};

module.exports = sidebars;